services:
  - type: web
    name: campus-placement-api
    env: python
    buildCommand: cd backend && pip install -r requirements.txt && python manage.py collectstatic --no-input
    startCommand: cd backend && python manage.py migrate --no-input && gunicorn placement_api.wsgi --bind 0.0.0.0:$PORT
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: PYTHON_VERSION
        value: "3.11.0"
